### ISSUE TITLE
有更動時，自動 build 到同個 repo 的 gh-pages

### ISSUE THREAD

**Issue by audreyt** [g0v/crowdfunding-gitbook#1]
之前有看到 grunt task ( grunt-build-gh-pages ) ，也許可以做成 post-commit hook 或 Travis CI hook?

**Comment by clkao** [comment]
see also https://github.com/rowoot/gulp-gh-pages/issues/38

**Comment by pm5** [comment]
https://github.com/g0v/crowdfunding-gitbook/commit/ea35865be0e6254c1ce55fefc1f6cb7f0a57b6c6 加了 gulp-gh-pages
hook 應該怎麼做比較好咧？

**Comment by clkao** [comment]
可以參考  https://github.com/g0v/env.g0v.tw/blob/master/.travis.yml 用 after_success
