### ISSUE TITLE
SEO 有幾頁空白

### ISSUE THREAD

**Issue by pm5** [g0v/crowdfunding-gitbook#3]
這頁空白： https://vtaiwan.tw/?_escaped_fragment_=/crowdfunding/1 ，應該是[簡介](https://vtaiwan.tw/#!/crowdfunding/1)才對。

這頁正常： https://vtaiwan.tw/?_escaped_fragment_=/crowdfunding/2

**Comment by yhsiang** [comment]
現在正常了
